export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREASE_QTY = 'INCREASE_QTY';
export const DECREASE_QTY = 'DECREASE_QTY';
export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS';

export const GETCATEGORIES_SUCCESS = 'GETCATEGORIES_SUCCESS';
export const GETCATEGORIES_FAILURE = 'GETCATEGORIES_FAILURE';
export const GETCATEGORIES_REQUEST = 'GETCATEGORIES_REQUEST';

export const CURRENCIES_SUCCESS = 'CURRENCIES_SUCCESS';
export const CURRENCIES_FAILURE = 'CURRENCIES_FAILURE';
export const CURRENCIES_REQUEST = 'CURRENCIES_REQUEST';

export const CHANGE_COLOR = 'CHANGE_COLOR';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const CHANGE_SIZE = 'CHANGE_SIZE';
export const CHANGE_CAPACITY = 'CHANGE_CAPACITY';
export const CHANGE_USB = 'CHANGE_USB';
export const CHANGE_TOUCH = 'CHANGE_TOUCH';

export const CLOTHES_SUCCESS = 'CLOTHES_SUCCESS';
export const CLOTHES_FAILURE = 'CLOTHES_FAILURE';
export const CLOTHES_REQUEST = 'CLOTHES_REQUEST';

export const TECH_SUCCESS = 'TECH_SUCCESS';
export const TECH_FAILURE = 'TECH_FAILURE';
export const TECH_REQUEST = 'TECH_REQUEST';

export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_FAILURE = 'ALL_PRODUCTS_FAILURE';
export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';

export const PRODUCTDETAILS_SUCCESS = 'PRODUCTDETAILS_SUCCESS';
export const PRODUCTDETAILS_FAILURE = 'PRODUCTDETAILS_FAILURE';
export const PRODUCTDETAILS_REQUEST = 'PRODUCTDETAILS_REQUEST';

export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
